steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/learn-361304/insurance-voice-frontend', '-f', 'frontend/Dockerfile', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/learn-361304/insurance-voice-frontend']
images:
- 'gcr.io/learn-361304/insurance-voice-frontend'
